security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    enable_authenticator_manager: true

    providers:
        customers:
            entity:
                class: App\Entity\Customer
                property: company

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            access_denied_handler: App\Security\AccessDeniedHandler
            pattern: ^/api/
            stateless: true
            provider: customers
            jwt: ~
        main:
            json_login:
                check_path: /auth
                username_path: company
                password_path: password

    access_control:
         - { path: ^/api/products, roles: ROLE_CUSTOMER }
         - { path: ^/api/customers, roles: ROLE_CUSTOMER }
         - { path: ^/api/users, roles: ROLE_CUSTOMER }



when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
